version: '3.7'

services:
    app:
        image: envase
        restart: always
        ports:
            - ${APP_PORT}:${APP_PORT}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_NAME: ${APP_NAME}
