apiVersion: v1
kind: Service
metadata:
    name: envase
    labels:
        app: envase
spec:
    type: LoadBalancer
    selector:
        app: envase
    ports:
        - protocol: TCP
          name: http
          port: 80
          targetPort: 4444
